version: "3.1"

services:
  mongo:
    image: mongo:8.0
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ligne8
      MONGO_INITDB_ROOT_PASSWORD: ligne8password
    volumes:
      - ./db_data/:/data/db/

  web:
    build: .
    container_name: rails_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://ligne8:ligne8password@mongo:27017/nlpf_trader